#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
# Update bootc containers (only x86_64)

# I trigger this with a SystemD timer once a week to keep my images up to
# date.

# Set field Separator
IFS=' '

# Which images should be built?
IMAGES=""

if [ -n $IMAGES ]; then
	for img in $IMAGES; do
		$HOME/.ci/bootc/bootc-build-x86_64 -p $img \
			-w $HOME/ci-build/$img-release \
			-t stable -b $(date -u +%Y%m%d.%H%M) -u
	done
else
	echo "No images specified."
fi
