#!/bin/bash
# SPDX-License-Identifier: GPL-2.0

# Update bootc containers

# I trigger this with a SystemD timer once a week to keep my images up to
# date.

# Set field Separator
IFS=' '

# Which images should be built?
IMAGES="mediajunkie nas4ipa gatekeeper-os"

for img in $IMAGES; do
	$HOME/.ci/bootc/bootc-build -p $img -w $HOME/ci-build/$img-release \
		-t stable -b UPD-$(date -u +%Y%m%d%H%M) -u
done
